name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# All pushes to main should trigger a fresh deployment.
# Assuming there are no force-pushes, cancelling the in-progress workflow
# will not cause any data loss.
concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
